Add Exit Command
BHoM/BHoM_Adapter pull request #303
Opened 2021-08-19 12:15 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #302

Adding new command for fully closing down linked open instance of the software.

### Test files

### Changelog

### Additional comments

2021-08-19 12:35 UTC, peterjamesnugent requested changes
Changes to descriptions.

2021-08-19 12:35 UTC, peterjamesnugent commented on Adapter_oM/ExecuteCommands/Exit.cs
> +        [Description("If set to true atempts to save any open file before exiting the software.")]
```suggestion
        [Description("If set to true, the adapter attempts to save any open file, closes the file and exits the software.")]
```

2021-08-19 12:35 UTC, peterjamesnugent commented on Adapter_oM/ExecuteCommands/Exit.cs
> +    [Description("Used to instruct the adapter to fully close down the running software. Adapter will generally not be useable after running this command.")]
```suggestion
    [Description("Used to instruct the adapter to exit the software. The adapter will generally not be useable after running this command as the link to the software will be broken.")]
```
Do we explicitly say that this command is different to the `Close` command?

2021-08-19 13:07 UTC, peterjamesnugent approved these changes
LGTM.

2021-08-19 13:08 UTC, peterjamesnugent commented
@BHoMBot check compliance

2021-08-24 07:21 UTC, IsakNaslundBh commented
@BHoMBot check required

2021-08-24 10:01 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3408494013

This is being done in agreement with @IsakNaslundBh following discussion and is approved as a valid dispensation for this work.

2021-08-24 10:01 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2021-08-24 10:04 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3409816604

Also done in discussion with @IsakNaslundBh to unblock this work for roll out of interop tests.

2021-08-24 10:05 UTC, merged